.\" $MirOS: contrib/hosted/tg/code/kwalletcli/kwalletaskpass.1,v 1.4 2010/11/16 09:11:15 tg Exp $
.\"-
.\" Copyright © 2009, 2010
.\"	Thorsten Glaser <tg@mirbsd.org>
.\"
.\" Provided that these terms and disclaimer and all copyright notices
.\" are retained or reproduced in an accompanying document, permission
.\" is granted to deal in this work without restriction, including un‐
.\" limited rights to use, publicly perform, distribute, sell, modify,
.\" merge, give away, or sublicence.
.\"
.\" This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
.\" the utmost extent permitted by applicable law, neither express nor
.\" implied; without malicious intent or gross negligence. In no event
.\" may a licensor, author or contributor be held liable for indirect,
.\" direct, other damage, loss, or other issues arising in any way out
.\" of dealing in the work, even if advised of the possibility of such
.\" damage or existence of a defect, except proven that it results out
.\" of said person’s immediate fault when using the work as intended.
.\"-
.\" Try to make GNU groff and AT&T nroff more compatible
.\" * ` generates ‘ in gnroff, so use \`
.\" * ' generates ’ in gnroff, \' generates ´, so use \*(aq
.\" * - generates ‐ in gnroff, \- generates −, so .tr it to -
.\"   thus use - for hyphens and \- for minus signs and option dashes
.\" * ~ is size-reduced and placed atop in groff, so use \*(TI
.\" * ^ is size-reduced and placed atop in groff, so use \*(ha
.\" * \(en does not work in nroff, so use \*(en
.ie \n(.g \{\
.	ds aq \(aq
.	ds TI \(ti
.	ds ha \(ha
.	ds en \(en
.\}
.el \{\
.	ds aq '
.	ds TI ~
.	ds ha ^
.	ds en \(em
.\}
.\" Implement .Dd with the Mdocdate RCS keyword
.rn Dd xD
.de Dd
.ie \\$1$Mdocdate: \{\
.	xD \\$2 \\$3, \\$4
.\}
.el .xD \\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \\$7 \\$8
..
.\"-
.Dd $Mdocdate: November 16 2010 $
.Dt KWALLETASKPASS 1
.Os
.Sh NAME
.Nm kwalletaskpass
.Nd kwallet-based pass-phrase dialog for use with OpenSSH
.Sh SYNOPSIS
.Nm
.Op Ar options
.Ar label
.Sh DESCRIPTION
.Nm
is a kwallet- and pinentry-based pass-phrase dialog for use with OpenSSH.
It is intended to be called from the
.Xr ssh\-add 1
programme and not invoked directly.
.Pp
If a passphrase is requested,
.Nm
works by first looking up the passphrase in the KWallet by means of
.Xr kwalletcli 1 ;
using it if found, then calling
.Xr kwalletcli_getpin 1
to interactively retrieve an answer from the user via
.Nm pinentry
otherwise.
If the user specifies a passphrase,
.Xr kwalletcli_getpin 1
is run again to ask if the passphrase should be stored in the KWallet.
If a confirmation instead of a passphrase is requested, it is merely relayed to
.Xr kwalletcli_getpin 1 .
.Pp
There are currently no options.
.Sh RETURN VALUES
.Nm
exits 0 on success, 1 if the user cancelled the dialogue,
or \*(Gt1 if an error occured.
.Sh ENVIRONMENT
.Bl -tag -width PINENTRY
.It Ev DISPLAY
The X11 server to use.
If this is unset or empty, calling
.Nm kwalletcli
is not attempted, because the KDE Wallet needs X11.
.It Ev PINENTRY
The
.Nm pinentry
programme to use.
The default is inherited from
.Xr kwalletcli_getpin 1 .
.El
.Sh SEE ALSO
.Xr kwalletcli 1 ,
.Xr kwalletcli_getpin 1 ,
.Xr ssh\-add 1 ,
.Xr ssh\-askpass 1
.Sh AUTHORS
.Nm
was written by
.An Thorsten Glaser Aq tg@mirbsd.org
mostly for tarent GmbH.
The idea came from an
.Pa askpass.C
file found somewhere on the 'net, with no author information.
Since it was licenced less freely, this is a rewrite from scratch;
modular and with more functionality, too.
