.\" $MirOS: contrib/hosted/tg/code/kwalletcli/kwalletcli.1,v 1.12 2010/11/16 09:16:08 tg Exp $
.\"-
.\" Copyright © 2009, 2010
.\"	Thorsten Glaser <tg@mirbsd.org>
.\"
.\" Provided that these terms and disclaimer and all copyright notices
.\" are retained or reproduced in an accompanying document, permission
.\" is granted to deal in this work without restriction, including un‐
.\" limited rights to use, publicly perform, distribute, sell, modify,
.\" merge, give away, or sublicence.
.\"
.\" This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
.\" the utmost extent permitted by applicable law, neither express nor
.\" implied; without malicious intent or gross negligence. In no event
.\" may a licensor, author or contributor be held liable for indirect,
.\" direct, other damage, loss, or other issues arising in any way out
.\" of dealing in the work, even if advised of the possibility of such
.\" damage or existence of a defect, except proven that it results out
.\" of said person’s immediate fault when using the work as intended.
.\"-
.\" Try to make GNU groff and AT&T nroff more compatible
.\" * ` generates ‘ in gnroff, so use \`
.\" * ' generates ’ in gnroff, \' generates ´, so use \*(aq
.\" * - generates ‐ in gnroff, \- generates −, so .tr it to -
.\"   thus use - for hyphens and \- for minus signs and option dashes
.\" * ~ is size-reduced and placed atop in groff, so use \*(TI
.\" * ^ is size-reduced and placed atop in groff, so use \*(ha
.\" * \(en does not work in nroff, so use \*(en
.ie \n(.g \{\
.	ds aq \(aq
.	ds TI \(ti
.	ds ha \(ha
.	ds en \(en
.\}
.el \{\
.	ds aq '
.	ds TI ~
.	ds ha ^
.	ds en \(em
.\}
.\" Implement .Dd with the Mdocdate RCS keyword
.rn Dd xD
.de Dd
.ie \\$1$Mdocdate: \{\
.	xD \\$2 \\$3, \\$4
.\}
.el .xD \\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \\$7 \\$8
..
.\"-
.Dd $Mdocdate: November 16 2010 $
.Dt KWALLETCLI 1
.Os
.Sh NAME
.Nm kwalletcli
.Nd command line interface to the KDE Wallet
.Sh SYNOPSIS
.Nm
.Op Fl q
.Fl hV
.Nm
.Op Fl q
.Fl f Ar folder
.Fl e Ar entry
.Op Fl P | p Ar password
.Sh DESCRIPTION
The
.Nm
utility is a command line interface to KWallet.
It will only work if KDE is running (DCOP) and reachable (via X11).
.Nm
can be used to get password entries from the Wallet,
or to write them there.
.Pp
The options are as follows:
.Bl -tag -width xPxpassword
.It Fl e Ar entry
Define the key
.Pq Ar entry
to use when accessing the Wallet.
Mandatory.
.It Fl f Ar folder
Set the
.Ar folder
to use when accessing the Wallet.
Mandatory.
.It Fl h
Display the usage.
.It Fl P
Read the password to write from standard input.
.It Fl p Ar password
Write
.Ar password
into the designated location in the Wallet.
.It Fl q
Be more quiet.
In combination with
.Fl V ,
do not display anything.
.It Fl V
Display the
.Nm
version information.
.El
.Pp
Default mode of operation, that is, unless
.Fl P
or
.Fl p
are used, is to read the password from the Wallet
and print it to standard output as-is, without any
trailing newline.
.Pp
All input and output is assumed to be in UTF-8.
.Sh RETURN VALUES
The
.Nm
utility exits 0 on success or \*(Gt0 if an error occurred:
.Bl -tag -width xxx
.It 1
The entry specified cannot be found (read access).
.It 2
The usage was shown.
.It 3
The Wallet could not be opened.
May be a missing DCOP connection.
Perhaps
.Ev DISPLAY
is not set.
.It 4
The folder specified cannot be found (read access).
.It 5
The folder specified cannot be opened.
.It 6
The value to the key specified could not be retrieved.
.It 8
An error occured trying to write the value.
.El
.Pp
The exit codes 1 and 4, on reading, are not fatal; they merely indicate
that the folder or entry specified does not exist.
The other errors are fatal and may be used to indicate the user that the
KWallet should not be used any more during the current session.
.Sh ENVIRONMENT
.Bl -tag -width DISPLAY
.It Ev DISPLAY
The X11 display to use for communicating with the KDE Wallet.
.El
.Sh SEE ALSO
.Xr kwalletcli_getpin 1
.Sh AUTHORS
.Nm
was written by
.An Thorsten Glaser Aq tg@mirbsd.org
mostly for tarent GmbH.
.Sh CAVEATS
Do not use
.Fl p Ar password
to store it, unless you absolutely must.
It is a security risk, because the command line invocation
is public information in a normal Unix environment.
Use
.Fl P
instead and provide the
.Ar password
on standard input.
.Pp
Beware of trailing newlines, especially outside of
.Xr mksh 1
scripts!
.Sh BUGS
If
.Ev DISPLAY
is not set, not valid, or
.Nm kdeinit
or
.Nm kdeinit4
cannot start for other reasons,
.Nm
may not recover gracefully.
In KDE 4 versions, this may even result in a Segmentation fault.
The author does not know of a way to catch this early; patches are welcome.
.Pp
There is no way (yet) to set a wallet other than the default wallet.
While this is a possible enhancement to the
.Nm
CLI, there is no feasible way to expose this functionality to the
various front-ends, such as
.Xr pinentry\-kwallet 1 ,
anyway, so the priority of fixing this is low.
