.\" $MirOS: contrib/hosted/tg/code/kwalletcli/pinentry-kwallet.1,v 1.2 2009/07/08 15:09:52 tg Exp $
.\"-
.\" Copyright © 2009
.\"	Thorsten Glaser <tg@mirbsd.org>
.\"
.\" Provided that these terms and disclaimer and all copyright notices
.\" are retained or reproduced in an accompanying document, permission
.\" is granted to deal in this work without restriction, including un‐
.\" limited rights to use, publicly perform, distribute, sell, modify,
.\" merge, give away, or sublicence.
.\"
.\" This work is provided “AS IS” and WITHOUT WARRANTY of any kind, to
.\" the utmost extent permitted by applicable law, neither express nor
.\" implied; without malicious intent or gross negligence. In no event
.\" may a licensor, author or contributor be held liable for indirect,
.\" direct, other damage, loss, or other issues arising in any way out
.\" of dealing in the work, even if advised of the possibility of such
.\" damage or existence of a defect, except proven that it results out
.\" of said person’s immediate fault when using the work as intended.
.\"-
.\" Try to make GNU groff and AT&T nroff more compatible
.\" * ` generates ‘ in groff, so use \`
.\" * ' generates ’ in groff, \' generates ´, so use \*(aq
.\" * - generates ‐ in groff, \- generates −, fixed in tmac/mdoc/doc-groff
.\"   thus use - for hyphens and \- for minus signs and option dashes
.\" * ~ is size-reduced and placed atop in groff, so use \*(TI
.\" * ^ is size-reduced and placed atop in groff, so use \*(ha
.\" * \(en does not work in nroff, so use \*(en
.ie \n(.g \{\
.	ds aq \(aq
.	ds TI \(ti
.	ds ha \(ha
.	ds en \(en
.\}
.el \{\
.	ds aq '
.	ds TI ~
.	ds ha ^
.	ds en \(em
.\}
.\" Implement .Dd with the Mdocdate RCS keyword
.rn Dd xD
.de Dd
.ie \\$1$Mdocdate: \{\
.	xD \\$2 \\$3, \\$4
.\}
.el .xD \\$1 \\$2 \\$3 \\$4 \\$5 \\$6 \\$7 \\$8
..
.\"-
.Dd $Mdocdate: July 8 2009 $
.Dt PINENTRY-KWALLET 1
.Os
.Sh NAME
.Nm pinentry-kwallet
.Nd kwallet-based pass-phrase dialog for use with GnuPG
.Sh SYNOPSIS
.Nm
.Op Ar options
.Sh DESCRIPTION
.Nm
is a kwallet- and pinentry-based pass-phrase dialog for use with GnuPG.
It is intended to be called from the
.Xr gpg-agent 1
daemon and not invoked directly.
.Pp
.Nm
replaces the regular
.Ic pinentry\-program
stanza set in
.Pa ~/.gnupg/gpg-agent.conf
and looks up the passphrases requested in the KWallet first, falling back to
.Nm pinentry
only if not found.
The user is given the option to store it in the KWallet afterwards.
.Pp
.Nm
talks the regular Aegypten protocol, as well as the undocumented
.Ic BYE
command, on stdio; all commands, even unknown ones, are passed through to a
.Nm pinentry
co-process during run-time, even if the latter is never used.
It accepts the same options as
.Nm pinentry ,
even unknown ones, because it is designed to plug in.
.Pp
.Nm
attempts sophisticated error handling:
if an error dialogue is displayed, an internal counter is increased.
If the counter reaches 2, the value stored in the KWallet is ignored,
and the user is asked anew.
The counter is stored in the KWallet, which is suboptimal but necessary,
because
.Xr gpg2 1
does not re-use the Aegypten sessions, instead spawning a new
.Nm
each time a passphrase is required (rather stupid).
Error counters are valid for 15 seconds since their last increasement.
.Sh RETURN VALUES
.Nm
exits 1 if it is called recursively, 0 if help or version
information are requested, and return codes do not matter
in any other cases because errors are signalled in-band.
It will exit 0 after the Aegypten session is terminated.
.Sh ENVIRONMENT
.Bl -tag -width PINENTRY
.It Ev DISPLAY
The X11 display to use for child processes.
.It Ev GPG_TERM
Terminal type of the current tty.
.It Ev GPG_TTY
The current terminal.
.It Ev PINENTRY
The
.Nm pinentry
programme to use.
Default:
.Dq pinentry
.El
.Sh SEE ALSO
.Xr date 1 ,
.Xr gpg-agent 1 ,
.Xr gpg2 1 ,
.Xr kwalletcli 1 ,
.Xr kwalletcli_getpin 1 ,
.Xr mksh 1 ,
.Xr pinentry-curses 1 ,
.Xr pinentry-gtk-2 1 ,
.Xr pinentry-qt 1 ,
.Xr pinentry-x11 1
.Sh AUTHORS
.Nm
was written by
.An Thorsten Glaser Aq tg@mirbsd.org
mostly for tarent GmbH.
